### ISSUE TITLE
"GPU buffer suballocator" commit broke terrain system on Intel iGPU

### ISSUE THREAD

**Issue by brakhane** [turanszkij/WickedEngine#1097]
I noticed that adding a terrain crashes on my linux laptop with Intel iGPU, the offending commit is 30917c9e1f205a01b7cf573cede68c0709876d67

The problem seems to be that here

```
#1  0x000055555765e8fd in wi::graphics::GraphicsDevice_Vulkan::CreateBuffer2 (this=0x523000005500, 
    desc=0x7fffab3ef460, init_callback=..., buffer=0x521000d112a0, alias=0x7fffab3ef620, alias_offset=0)
    at /home/dennis/src/WickedEngine/WickedEngine/wiGraphicsDevice_Vulkan.cpp:3966
3966                            buffer->mapped_data = internal_state->allocation->GetMappedData();
```

`internal_state->allocation` is nullptr.

<details><summary>Full stacktrace</summary>

```
#0  0x00005555575fa57d in VmaAllocation_T::GetMappedData (this=0x0)
    at /home/dennis/src/WickedEngine/WickedEngine/Utility/vk_mem_alloc.h:11031
#1  0x000055555765e8fd in wi::graphics::GraphicsDevice_Vulkan::CreateBuffer2 (this=0x523000005500, 
    desc=0x7fffab3ef460, init_callback=..., buffer=0x521000d112a0, alias=0x7fffab3ef620, alias_offset=0)
    at /home/dennis/src/WickedEngine/WickedEngine/wiGraphicsDevice_Vulkan.cpp:3966
#2  0x0000555558159599 in wi::scene::MeshComponent::CreateRenderData (this=0x521000d11100)
    at /home/dennis/src/WickedEngine/WickedEngine/wiScene_Components.cpp:1301
#3  0x000055555819e492 in operator() (__closure=0x7fffab114440, args=...)
    at /home/dennis/src/WickedEngine/WickedEngine/wiScene_Serializers.cpp:536
#4  0x00005555581b9f1d in std::__invoke_impl<void, wi::scene::MeshComponent::Serialize(wi::Archive&, wi::ecs::EntitySerializer&)::<lambda(wi::jobsystem::JobArgs)>&, wi::jobsystem::JobArgs>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/13/bits/invoke.h:61
#5  0x00005555581b918e in std::__invoke_r<void, wi::scene::MeshComponent::Serialize(wi::Archive&, wi::ecs::EntitySerializer&)::<lambda(wi::jobsystem::JobArgs)>&, wi::jobsystem::JobArgs>(struct {...} &) (__fn=...)
    at /usr/include/c++/13/bits/invoke.h:111
#6  0x00005555581b8780 in std::_Function_handler<void(wi::jobsystem::JobArgs), wi::scene::MeshComponent::Serialize(wi::Archive&, wi::ecs::EntitySerializer&)::<lambda(wi::jobsystem::JobArgs)> >::_M_invoke(const std::_Any_data &, wi::jobsystem::JobArgs &&) (__functor=..., __args#0=...) at /usr/include/c++/13/bits/std_function.h:290
#7  0x00005555578cebdb in std::function<void(wi::jobsystem::JobArgs)>::operator() (this=0x7fffab114440, 
    __args#0=...) at /usr/include/c++/13/bits/std_function.h:591
#8  0x00005555578cd72f in wi::jobsystem::Job::execute (this=0x7fffae1bbb40)
    at /home/dennis/src/WickedEngine/WickedEngine/wiJobSystem.cpp:53
#9  0x00005555578cdeb8 in wi::jobsystem::PriorityResources::work (
    this=0x55555b65d8a8 <wi::jobsystem::internal_state+232>, startingQueue=2)
    at /home/dennis/src/WickedEngine/WickedEngine/wiJobSystem.cpp:102
#10 0x00005555578b92c7 in operator() (__closure=0x5030000b4078)
    at /home/dennis/src/WickedEngine/WickedEngine/wiJobSystem.cpp:234
#11 0x00005555578cd17e in std::__invoke_impl<void, wi::jobsystem::Initialize(uint32_t)::<lambda()> >(std::__invoke_other, struct {...} &&) (__f=...) at /usr/include/c++/13/bits/invoke.h:61
#12 0x00005555578cd141 in std::__invoke<wi::jobsystem::Initialize(uint32_t)::<lambda()> >(struct {...} &&) (
    __fn=...) at /usr/include/c++/13/bits/invoke.h:96
#13 0x00005555578cd0ee in std::thread::_Invoker<std::tuple<wi::jobsystem::Initialize(uint32_t)::<lambda()> > >::--Type <RET> for more, q to quit, c to continue without paging--
_M_invoke<0>(std::_Index_tuple<0>) (this=0x5030000b4078) at /usr/include/c++/13/bits/std_thread.h:292
#14 0x00005555578cd0c2 in std::thread::_Invoker<std::tuple<wi::jobsystem::Initialize(uint32_t)::<lambda()> > >::operator()(void) (this=0x5030000b4078) at /usr/include/c++/13/bits/std_thread.h:299
#15 0x00005555578cd0a6 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<wi::jobsystem::Initialize(uint32_t)::<lambda()> > > >::_M_run(void) (this=0x5030000b4070) at /usr/include/c++/13/bits/std_thread.h:244
#16 0x00007ffff755b224 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#17 0x00007ffff79281d6 in asan_thread_start (arg=0x7fffafad8000)
    at ../../../../src/libsanitizer/asan/asan_interceptors.cpp:234
#18 0x00007ffff71f7b7b in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:448
#19 0x00007ffff72757b8 in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

```
</details>

**Comment by turanszkij** [comment]
Fixed, thanks for reporting it.

**Comment by brakhane** [comment]
Unfortunately, the fix didn't work. The problem still exists, nothing seems to have changed.

**Comment by turanszkij** [comment]
Oops, looks like there were two parts for this issue, the above commit fixed it on DX12 but not on Vulkan. This commit fixes it on Vulkan: https://github.com/turanszkij/WickedEngine/commit/3ee7f0d85e04395481bf375b4c9e6c324fb71f19

**Comment by brakhane** [comment]
Yep, that has fixed it. Thanks!
