### ISSUE TITLE
D3D12 Device Remove : Device Hung

### ISSUE THREAD

**Issue by Cop46** [turanszkij/WickedEngine#623]
There is a bug in the engine with dx12.
Sometimes that work sometimes that crash with D3D12 Device Remove : DXGI_ERROR_DEVICE_HUNG.
I have noticed this crash arrived when I remove meshes with entity_remove. Tested with two differents computers on Win11 with RTX 2080S and Win11 RTX3070TI. 
That appear to be working well on Win10 ???
Other users have reported this bug on discord that arrived when loading scene like Sponza with a Radeon 6800U and updated drivers.
If anyone have this bug, that was cool to report this here to find where it is and how to fix it.

**Comment by turanszkij** [comment]
Sorry, I couldn't repro this, but I have Win10.

**Comment by Enzojz** [comment]
I am trying to create a simplest window with engine, like the ImGUI example, even simplier, without anything about ImGUI, just the teapot rendered with RenderPath3D.

When I replace RenderPath3D with RenderPath3D_PathTracing, I come to the same error.

I am also on Windows 11, RTX 2070s.

My renderer:

  module;
  #include "stdafx.h"
  export module renderer;
  
  namespace RailwaySandbox {
	  export class Renderer : public wi::RenderPath3D {
		  wi::gui::Label label;
	  public:
		  void Load() override;
		  void Update(float dt) override;
		  void ResizeLayout() override;
		  void Render() const override;
	  };
  
	  void Renderer::Load() {
		  setSSREnabled(false);
		  setReflectionsEnabled(true);
		  setFXAAEnabled(false);
  
		  // Reset all state that tests might have modified:
		  wi::eventhandler::SetVSync(true);
		  wi::renderer::SetToDrawGridHelper(false);
		  wi::renderer::SetTemporalAAEnabled(true);
		  wi::renderer::ClearWorld(wi::scene::GetScene());
		  wi::scene::GetScene().weather = wi::scene::WeatherComponent();
		  this->ClearSprites();
		  this->ClearFonts();
		  if (wi::lua::GetLuaState() != nullptr) {
			  wi::lua::KillProcesses();
		  }
  
		  // Reset camera position:
		  wi::scene::TransformComponent transform;
		  transform.Translate(XMFLOAT3(0, 2.f, -4.5f));
		  transform.UpdateTransform();
		  wi::scene::GetCamera().TransformCamera(transform);
  
		  // Load model.
		  wi::scene::LoadModel("../Content/models/teapot.wiscene");
  
		  RenderPath3D::Load();
	  }
  
	  void Renderer::Update(float dt) {
		  RenderPath3D::Update(dt);
	  };
  
	  void Renderer::Render() const {
		  RenderPath3D::Render();
	  };
  
	  void Renderer::ResizeLayout() {
		  RenderPath3D::ResizeLayout();
		  float screenW = GetLogicalWidth();
		  float screenH = GetLogicalHeight();
		  label.SetPos(XMFLOAT2(screenW / 2.f - label.scale.x / 2.f, screenH * 0.95f));
	  };
  }

**Comment by Cop46** [comment]
I think the pathTracing error is not the same issue...
I have identified one cause of this bug, this is  "SurfelGI" !
And other type of similar bug is when removing the Terrain but I think this is not the same bug but same result.

https://github.com/user-attachments/assets/3c36119f-e544-42b5-8c27-04f5692a6382


https://github.com/user-attachments/assets/d2d5a5c1-dc45-46a5-9ec7-b0d026f22b27

**Comment by turanszkij** [comment]
The terrain hang is fixed here: https://github.com/turanszkij/WickedEngine/commit/098d7f61597c61234050d901c96431b639f1de8f
The other one I couldn't repro, so can you send me the model either here or private message?

**Comment by Cop46** [comment]
Sended a private message on discord because this model is not free.

**Comment by turanszkij** [comment]
Should be fixed with that model you sent, thanks.

**Comment by Cop46** [comment]
This bug is not fixed,
If you not select all meshes for deleting, the crash is always here...

https://github.com/user-attachments/assets/d6f98775-c5d2-44b3-bdc3-60779fc6ca6c

**Comment by turanszkij** [comment]
Please try the above commit and see if the hang still persists.

**Comment by Cop46** [comment]
Fixed !!! Many thanks and keep up the good work :)
